[deploy]
bucket = 'cfn-artifacts-awsbc.flyingresnova.com'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'awsbc.flyingresnova.com'
EnvBackendUrl = 'api.awsbc.flyingresnova.com'