AWSTemplateFormatVersion: "2010-09-09"

Description: |
  The networking and cluster configuration to support fargate containers
  - ECS Fargate Cluster
  - Application Load Balancer (ALB)
    - ipv4
    - internet facing
  - ALB Security Group
  - HTTPS Listener 
    - send naked domain to frontend target group
    - send api. subdomain to backend target group
  - HTTP Listener
    - redirect to HTTPS listener
  - Backend Target group
  - Frontend Target group

Parameters:

  CertificateArn:
    Type: String

Resources:
  ECSCluster: #LogicalName
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html

    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub "${AWS::StackName}FargateCluster"
      CapacityProviders:
        - FARGATE
    ClusterSettings:
        - Name: containerInsights
          Value: enabled
    Configuration:
      ExecuteCommandConfiguration:
        # KmsKeyId: !Ref KmsKeyId
        Logging: DEFAULT
    ServiceConnectDefaults:
      Namespace: cruddur

   ALB:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: !Sub "${AWS::StackName}ALB"
      Type: application
      IpAddressType: ipv4
      Schema: internet-facing
      SecurityGroups:
        - SG ID
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html
      LoadBalancerAttributes:
        - Name: routing.http2.enabled
          Value: true
        - Name: routing.http.preserve_host_header.enabled
          Value: false
        - Name: deletion_protection.enabled
          Value: true
        - Name: load_balancing.cross_zone.enabled
          Value: true
        - Name: access_logs.s3.enabled
          Value: false
        # In-case we want to turn on logs
        # - Name: access_logs.s3.bucket
        #   Value: bucket-name
        # - Name: access_logs.s3.prefix
        #   Value: ""

    HTTPSListener:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties: 
        Protocol: HTTPS
        Port: 443
        LoadBalancerArn: !Ref ALB
        Certificates:
          - CertificateArn: !Ref CertificateArn 
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref FrontendTG
        
        
        

    HTTPListener: 
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties:    
        Protocol: HTTP
        Port: 80
        LoadBalancerArn: !Ref ALB
        DefaultActions:
          - Type: "redirect"
            RedirectConfig:
              Protocol: "HTTPS"
              Port: 443
              Host: "#{host}"
              Path: "/#{path}"
              Query: "#{query}"
              StatusCode: "HTTP_301"
            
        
        


Outputs: