[deploy]
bucket = 'cfn-artifacts-awsbc.flyingresnova.com'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'astroveny/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-artifacts-awsbc.flyingresnova.com"