[deploy]
bucket = 'cfn-artifacts-awsbc.flyingresnova.com'
region = 'us-east-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:235696014680:certificate/176ff77a-df46-4158-83dd-58ab4916c583'
WwwBucketName = 'www.awsbc.flyingresnova.com'
RootBucketName = 'awsbc.flyingresnova.com'